- hosts: all
  become: yes
  user: administrator
  gather_facts: no
  pre_tasks:
  - name: 'Atualizando o repo'
    raw: 'apt -y update'
  - name: 'Pacotes necessários k8s'
    raw: 'apt -y install apt-transport-https ca-certificates curl gnupg'
  - name: 'Desabilitando o SWAP'
    raw: 'swapoff -a && sed -i /swap/d /etc/fstab'
  roles:
  - { role: install-k8s, tags: ['install_k8s_role'] }

- hosts: k8s-master
  become: yes
  user: administrator
  roles: 
  - { role: create-cluster, tags: ['create_cluster_role'] }

- hosts: k8s-workers
  become: yes
  user: administrator
  roles:
  - { role: join-workers, tags: ['join_workers_role'] }